name: Automatic CipherOS Builder

on:
  push:
    branches:
      - main

env:
  VERSION: 1.6

jobs:
  test-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64, x32]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Run Compilation Script Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd startup
          ./compile-startup.bat

      - name: Test Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd startup
          ./dist/redline.exe

      - name: Test Ubuntu
        if: runner.os == 'ubuntu'
        shell: bash
        run: |
          cd startup
          ./dist/redline
      
      - name: Test macOS
        if: runner.os == 'macos'
        shell: bash
        run: |
          cd startup
          ./dist/redline

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}-build"
          path: "startup/dist"
          include-hidden-files: true